#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: 1
#          uri: http://localhost:8081/
#          predicates:
#            - Path= /customers/**
#        - id: 2
#          uri: http://localhost:8082/
#          predicates:
#            - Path= /products/**
#    discovery:
#      enabled: true
#
#server:
#  port: 8888


spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "*"